config/routes.rb
Rails.application.routes.draw do

   root 'static_pages#Home'

     resources :rsvps
     resources :users

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
	validates :name, :selection,  presence: true
	validates :email, presence: true,
                    length: { minimum: 5 }
					#uniqueness: true
	validates :guests, numericality: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :attending, presence: true
  validates :food, :meal, presence: true, if: :chose_attending?
  validates :food_restrictions, presence:true, if: :chose_restrictions?

  def chose_attending?
    attending == "Yes"
  end

  def chose_restrictions?
    food == "Yes"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protected
    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == USER_ID && password == PASSWORD
      end
    end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
	before_filter :authenticate, :only => [:index]
	layout "rsvp"

	def index
		@rsvp = Rsvp.all
	end

	def new
		@rsvp = Rsvp.new
	end

	def create
		@rsvp = Rsvp.new(rsvp_params)
		if @rsvp.save
			 # Tell the UserMailer to send a welcome email after save
			NewUserMailer.welcome_email(@rsvp).deliver_now
			render 'thanks'
		else
			render 'new'
		end
	end

	def destroy
		@rsvp = Rsvp.find(params[:id])
		@rsvp.destroy
		render 'deleted'
	end

private
	def rsvp_params
		params.require(:rsvp).permit(:name,:email,:selection,:guests,:guest_names,:comments)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def Home
    @rsvp = Rsvp.new
    @greeting = "Hello Everyone"
    @blurb = "Please join us"
    @user = User.all
  end


  def WeddingParty
  end

  def Location
    @greeting = "Hello Everyone"
    @blurb = "Please join us"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "rsvp"

  def index
	  @user = User.all
  end

  def new
    @user = User.new[user_params]
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      NewUserMailer.welcome_email(@user).deliver_now
      NewUserMailer.notifier(@user).deliver_now
      respond_to do |format|
        format.html {render :nothing => true}
      end
    else
      format.json render :nothing => true
    end
  end

  def show
      @user = User.find(params[:id])
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :attending, :meal,:food, :food_restrictions, :comments, :not_coming)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Colin & Sarah's Wedding</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Arizonia' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body class='grey lighten-4'>
 <div class="navbar-fixed">
  <nav id='nav' >
   <div class="nav-wrapper red darken-1">
     <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
     <div class="container ">
       <a  class="navbar-brand page-scroll" href="#home">Home</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          
          <li ><a class='page-scroll' href="#bridegroom">bride&groom</a></li>
          <li><a class='page-scroll' href="#weddingparty">wedding party</a></li>
          <li><a class='page-scroll' href="#details">details</a></li>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><a class='page-scroll' href="#bridegroom">bride&groom</a></li>
          <li><a class='page-scroll' href="#weddingparty">wedding party</a></li>
          <li><a class='page-scroll' href="#details">details</a></li>
        </ul>
       </div>
      </div>
  </nav>
 </div>


    <%= yield %>

    <footer class="page-footer red darken-4">
      <div class="container ">
        <%= mail_to "wedding@colinandsarah.ca", "Email: wedding@colinandsarah.ca", class:'white-text' %>
      </div>
    </footer>
</body>
</html>

app/views/layouts/rsvp.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Colin & Sarah's Wedding</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body class='grey lighten-4'>
 <div class="navbar-fixed">
  <nav id='nav'>
   <div class="nav-wrapper red base">
     <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
     <div class="container">
     	<%= link_to "Home", root_url %>
        <ul class="side-nav" id="mobile-demo">
          <%= link_to "Home", root_url %>
        </ul>
       </div>
      </div>
  </nav>
 </div>

    <%= yield %>

</body>
</html>

app/views/rsvps/_form.html.erb
<div class="container">
  <h1 class="text-center">Please RSVP</h1>

  <% if @rsvp.errors.any? %>
  <div class="row red-text">
    <ul>
      <% @rsvp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <!--<form class="form-horizontal"> -->
    <%=form_for @rsvp do |f| %>
      <form>
          <!-- Name -->
          <div class="input-field">
          <i class="mdi-action-account-circle prefix"></i>
          <%=f.label :name, "Name:" %>
          <%=f.text_field :name, class: "validate" %>
        </div>

          <!-- Email -->
         <div class="input-field">
          <i class="mdi-communication-email prefix"></i>
          <%=f.label :email, "Email: "%>
          <%=f.email_field :email, class: "validate" %>
            </div>


          <!-- Coming? -->
        <div>
          <p>Attending:</p>

            <%=f.radio_button :selection,   "Yes"  %>
            <%=f.label :selection, "Yes", id:'radio_yes', value:"Yes"%>

            <%=f.radio_button :selection, "No"  %>
            <%=f.label :selection, "No", id:'radio_no', value:"No" %>
        </div>

            <!-- # of guests -->
        <div class='attending'>
          <div class="input-field">
            <%=f.label :guests, "Number of guests in your party: " %>
            <%=f.text_field :guests, class: "validate" %>
          </div>

            <!-- Food Restrictions -->
          <div class="input-field">
           <%=f.label :guest_names, "Food Restrictions: " %>
           <%=f.text_area :guest_names, class: "materialize-textarea"%>
          </div>

            <!-- Comments -->
          <div class="input-field">
           <%=f.label :comments, "Comments for the Bride and Groom " %>
           <%=f.text_area :comments, class: "materialize-textarea"%>
          </div>
        </div>


            <!-- Not attending Comments -->
        <div class="not-attending ">
          <div class="input-field">
            <%=f.label :comments, "Aww, :( Please feel free to leave a message for us! " %>
              <%=f.text_area :comments, class: "materialize-textarea" %>
                <div class="col-sm-8 "></div>
          </div>
        </div>

          <!-- Submit Button-->
        <div>
            <%= button_tag( :class => "z-depth-2 btn waves-effect waves-light") do %>
             Submit <i class="mdi-content-send right"></i>
            <% end %>
        </div>
        </form>

  <% end %>
</div>

app/views/rsvps/deleted.html.erb
<h1>Successfully Deleted!</h1>

<%= link_to 'Back', index_rsvps_path %>

app/views/rsvps/index.html.erb
<div class="container">
<h1>List of RSVPs</h1>
<table class="responsive-table hoverable">
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Email</th>
    <th>Coming?</th>
    <th># of guests</th>
    <th>Food Restrictions</th>
    <th>Comments for us :)</th>
    <th colspan="2"></th>
  </tr>
  <% @rsvp.each do |rsvp| %>
    <tr>
      <td>
        <%= rsvp.id %>
      </td>
      <td>
        <%=rsvp.name %>
      </td>
      <td>
        <%=rsvp.email %>
      </td>
      <td>
        <%=rsvp.selection %>
      </td>
      <td>
        <%=rsvp.guests %>
      </td>
      <td>
        <%=rsvp.food_restrictions %>
      </td>
      <td>
        <%=rsvp.comments %>
      </td>
      <td>
        <%=rsvp.created_at.strftime('%Y-%m-%d %H-%M-%S') %>
      </td>
      <td>
        <%=link_to "Delete", rsvp_path(rsvp), method: :delete, data: {confirm: "Are you sure?"} %>
    </tr>
    <% end %>
</table>
<%=link_to "Back", new_rsvp_path %>
</div>

app/views/rsvps/new.html.erb
<div class="container">
	<%= render 'form' %>
</div>

app/views/rsvps/thanks.html.erb
<div class="container">
<div class="row"></div>
	<h1>Thanks for RSVPing!</h1>
	<p>You will recieve an email confirmation shortly, if you do not receive an email within the hour please email Colin</p>
	<%= link_to 'Back', static_pages_Home_path %>
</div>

app/views/static_pages/Home.html.erb
<div class='row'>
  <div class='col hide-on-small-only m3 l2'>
    <div id='countdown-wrapper' class="pinned">
      <%=render '/static_pages/partials/countdown' %>
    </div>
      </div>
 <div id="banner" class="row">
	   <section id='home' class='section scrollspy'>
		   		<div class='col s12 m12 l6 offset-l8 right'>
  			   	<div id='rsvp-card' class='card right'>
  						<%= render partial: '/users/partials/table' %>
			    </div>
		   </div>
	   </section>
</div>

  <section id="bridegroom" class='section scrollspy'>
      <%=render '/static_pages/partials/bridegroom' %>
  </section>

  <div class='hide-on-med-and-down'>
    <div id="index-banner" class="parallax-container">
      <div class="parallax"><%=image_tag('parallax2.jpg')%></div>
    </div>
  </div>

  <section id="weddingparty" class='section scrollspy'>
    <%=render '/static_pages/partials/weddingparty' %>
  </section>

<div class='hide-on-med-and-down'>
   <div id="index-banner" class="parallax-container ">
    <div class="parallax"><%=image_tag('parallax3.jpg')%></div>
  </div>
</div>

    <section id="details" class='section scrollspy'>
      <%=render '/static_pages/partials/details' %>
    </section>

app/views/static_pages/partials/_bridegroom.html.erb
<div class="container">
<h1>Bride & Groom</h1>
<div class="row">
<!-- Sarah McCarville -->
	<div class="col s12 m12 l6">
		<div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag('sarah.jpg', class:'activator') %>
        </div>
        <div class="card-content center-align">
          <span class="card-title activator grey-text text-darken-4">Sarah McCarville</span>
          <p><a href="#">The Bride</a></p>
        </div>

			</div>
    </div>

<!-- Colin Montgomery -->
	<div class="col s12 m12 l6">
		 <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag('colin.jpg', class:'activator') %>
        </div>
        <div class="card-content center-align">
          <span class="card-title grey-text text-darken-4 ">Colin Montgomery</span>
          <p><a href="#">The Groom</a></p>
        </div>
      </div>
	  </div>
	</div>
  </div>

app/views/static_pages/partials/_contact.html.erb
<div class='container'>
  <h1>Contact:</h1>
  <div class='card-panel'>
      <p>Phone:(587) 998-8842</p>
      <p>Email:wedding@colinandsarah.ca</p>
  </div>

</div>

app/views/static_pages/partials/_details.html.erb
<div class="container">
	<h1>Details</h1>
	<div class="row">
		<div class="col s12 m12 l4 center">
			<div class="card">
				<div class='card-image'>
					<%= image_tag ('schedule.jpg') %>
					<span class="card-title">Schedule</span>
				</div>
				<ul>
					<li>Ceremony: 2:30pm</li>
					<li>Reception: 6:00pm</li>
					<li>Dance: 9:00pm</li>
				</ul>
			</div>
		</div>
		<div class='col s12 m12 l4 center'>
			<div class="card">
				<div class="card-image">
					<%=image_tag('shipyard.jpg') %>
					<span class="card-title">Location</span>
				</div>
					<p class='center'>
						Shipyard Market</br>370 Water St, Summerside, PE </br>C1N 1C4
					</p>
			</div>
		</div>
	<div class='col s12 m12 l4 center'>
		<div class="card">
			<div class='card-image'>
				<%= image_tag('loyalist.jpg') %>
				<span class="card-title">Hotels</span>
			</div>
			<ul>
				<li>Loyalist</li>
				<li>Linkletter</li>
				<li>Quality Inn</li>
			</ul>
		</div>
	</div>
</div>

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5503.595989711357!2d-63.788634804316665!3d46.39323145700509!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0x5deec1f56a727999!2sLobster+House+Restaurant+%26+Oyster+Bar!5e0!3m2!1sen!2sca!4v1431978022757" class="z-depth-2 embed-responsive-item" width="100%" height = "400"
max-width="65%"  frameborder="0" style="border:0"></iframe>
</div>
</div>
</div>
</div>

app/views/static_pages/partials/_weddingparty.html.erb
<div class='container'>
	<h1>Wedding Party</h1>
	<!--Cody & Emily-->
	<div class="row"	>
	<div class="col s12 m12 l6">
	  <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag('cody.jpg', class:'activator') %>
        </div>
        <div class="card-content center-align">
          <span class="card-title activator grey-text text-darken-4">Cody Montgomery</span>
          <p><a href="#">Best Man</a></p>
        </div>

				</div>
      </div>

		<div class="col s12 m12 l6">
	   <div class="card ">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag('emily.jpg', class:'activator') %>
        </div>
        <div class="card-content center-align">
          <span class="card-title activator grey-text text-darken-4">Emily McCarville</span>
          <p><a href="#">Maid of Honor</a></p>
        </div>

      </div>
		</div>
	  </div>

	  <!-- Josh & Amanda -->

			<div class="row">
			<div class="col s12 m12 l6">
	   <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag('josh.jpg', class:'activator') %>
        </div>
        <div class="card-content center-align">
          <span class="card-title activator grey-text text-darken-4">Josh Harvey</span>
          <p><a href="#">Groomsman</a></p>
        </div>

				</div>
      </div>


	<div class="col s12 m12 l6">
	   <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag('amanda.jpg', class:'activator') %>
        </div>
        <div class="card-content center-align">
          <span class="card-title activator grey-text text-darken-4">Amanda Lefurgey</span>
          <p><a href="#">Bridesmaid</a></p>
        </div>

      </div>
			</div>
	  </div>

	  <!-- Andrew & Becca-->

			<div class="row">
				<div class="col s12 m12 l6">
	   <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag('andrew.jpg', class:'activator') %>
        </div>
        <div class="card-content center-align">
          <span class="card-title activator grey-text text-darken-4">Andrew McCarville</span>
          <p><a href="#">Groomsman</a></p>
        </div>

				</div>
      </div>


	<div class="col s12 m12 l6">
	   <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag('becca.jpg', class:'activator') %>
        </div>
        <div class="card-content center-align">
          <span class="card-title activator grey-text text-darken-4">Becca Griffin</span>
          <p><a href="#">Bridesmaid</a></p>
        </div>

      </div>
			</div>
	  </div>

	  <!-- Willie & Kate -->

			<div class="row">
		<div class="col s12 m12 l6">
	   <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag('willie.jpg', class:'activator') %>
        </div>
        <div class="card-content center-align">
          <span class="card-title activator grey-text text-darken-4">Willie Macguigan</span>
          <p><a href="#">Groomsman</a></p>
        </div>

				</div>
      </div>


	<div class="col s12 m12 l6">
	   <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag('katelyn.jpg', class:'activator') %>
        </div>
        <div class="card-content center-align">
          <span class="card-title activator grey-text text-darken-4">Katelyn Kelly</span>
          <p><a href="#">Bridesmaid</a></p>
        </div>

      </div>
	  </div>
</div>

app/views/users/edit.html.erb
<div class="modal-content">
	<div class="container">


<!--<form class="form-horizontal"> -->
	<%=form_for @user, url: user_path(@user), method: :patch, remote:true, :html => { :'data-type' => 'html', :id => 'edit-user-form' } do |f| %>

	<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


      <form>
		<div class='row'>
          <!-- Name -->
			<div class='col s12 m12 l6'>
				<h2 class='flow-text'><%=@user.name%>!</h2>
			</div>
			<div class='col s12 m12 l6'>
				<!--Attending-->
				<div>
						<p>Attending:</p>

						<%=f.radio_button :attending,   "Yes"  %>
						<%=f.label :attending, "Yes", id:'radio_yes', value:"Yes"%>

						<%=f.radio_button :attending, "No"  %>
						<%=f.label :attending, "No", id:'radio_no', value:"No" %>
				</div>
			</div>
		</div>
		<!-- Attending -->
<div class="attending">
		<div class='row'>
		 <!-- Email -->
			<div class='col s12 m12 l6'>
        <div class="input-field">
					<i class="mdi-communication-email prefix"></i>

					 <%=f.label :email, "Email"%>
					 <%=f.email_field :email, value: "#{@user.email}", class: "validate" %>
			  </div>
			</div>
            <!-- Meal Choice -->
			<div class='col s12 m12 l6'>
          <p>Meal Selection:</p>

			   <%=f.radio_button :meal,   "Turkey"  %>
			   <%=f.label :meal, "Turkey", value:"Turkey"%>

			   <%=f.radio_button :meal, "Haddock"  %>
			   <%=f.label :meal, "Haddock", value:"Haddock" %>
      </div>
		</div>
	<div class='row'>
	<!-- Food Restrictions -->
		<div class='col s12 m12 l6'>
			<div class="input-field" id='restrictions'>
				<%=f.label :food_restrictions, "" %>
				<%=f.text_area :food_restrictions, class: "materialize-textarea"%>
			</div>

		</div>

		<div id='food-yes-no' class='col s12 m12 l6 offset-l6'>
			<p>Food Restrictions:</p>
			<%=f.radio_button :food, "Yes"  %>
			<%=f.label :food, "Yes",id:'food_yes', value:"Yes"%>

			<%=f.radio_button :food, "No"  %>
			<%=f.label :food, "No", id:'food_no', value:"No" %>
		</div>
	</div>


	<!-- Comments -->
	<div class='row'>
	<div class='col s12 m12 l12'>
		<div class="attending">
          <div class="input-field">
           <%=f.label :comments, "Comments for the Bride and Groom " %>
           <%=f.text_area :comments, class: "materialize-textarea"%>
          </div>
			</div>
		</div>
  </div>
</div>

            <!-- Not attending  -->
        <div class="not-attending ">
					<div class='row'>

						<!-- Not attending comments -->
						<div class='center-align'>
		          <div class="input-field">
		            <%=f.label :not_coming, "Aww, :( Please feel free to leave a message for us! " %>
		              <%=f.text_area :not_coming, class: "materialize-textarea" %>
		                <div class="col-sm-8 "></div>
		          </div>
						</div>

						</div>
	        </div>

          <!-- Submit Button-->
        <div class='row'>
					<div class='center-align'>
            <%= button_tag( id: "form-modal-submit", :class => "rsvp-submit z-depth-2 btn waves-effect waves-light", data: { disable_with: "Please wait...", modal:"#myModal_#{@user.id}", name:@user.name, email:@user.email}) do %>
             Submit <i class="mdi-content-send right"></i>
            <% end %>
					</div>
        </div>
        </form>
  <% end %>

	</div>
</div>

app/views/users/partials/_edit.html.erb
<div class="modal-content" id='rsvp-modal'>
	<div class="container">
			<div class="card">


<!--<form class="form-horizontal"> -->
	<%=form_for user, url: user_path(user), method: :patch, remote:true, :html => { :'data-type' => 'html', :id => 'edit-user-form' } do |f| %>

	<% if user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(user.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
    <% user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


      <form>
		<div class='row'>
          <!-- Name -->
			<div class='col s12 m12 l12'>
				<h2 class='flow-text'><%=user.name%>!</h2>
			</div>
			<div class='col s12 m12 l12'>
				<!--Attending-->
				<div>
						<p>Attending:</p>

						<%=f.radio_button :attending,   "Yes"  %>
						<%=f.label :attending, "Yes", id:'radio_yes', value:"Yes"%>

						<%=f.radio_button :attending, "No"  %>
						<%=f.label :attending, "No", id:'radio_no', value:"No" %>
				</div>
			</div>
		</div>
		<div class='row'>
		 <!-- Email -->
			<div class='col s12 m12 l12'>
				<div class="input-field">
					<i class="mdi-communication-email prefix"></i>

					 <%=f.label :email, "Email"%>
					 <%=f.email_field :email, value: "#{user.email}", class: "validate" %>
				</div>
			</div>
		</div>
		<!-- Attending -->
<div class="attending">

				<div class='row'>
            <!-- Meal Choice -->
			<div class='col s12 m12 l12'>
          <p>Meal Selection:</p>

			   <%=f.radio_button :meal,   "Turkey"  %>
			   <%=f.label :meal, "Turkey", value:"Turkey"%>

			   <%=f.radio_button :meal, "Haddock"  %>
			   <%=f.label :meal, "Haddock", value:"Haddock" %>
      </div>
		</div>
	<div class='row'>
	<!-- Food Restrictions -->
		<div id='food-yes-no' class='col s12 m12 l12'>
			<p>Food Restrictions:</p>
			<%=f.radio_button :food, "Yes"  %>
			<%=f.label :food, "Yes",id:'food_yes', value:"Yes"%>

			<%=f.radio_button :food, "No"  %>
			<%=f.label :food, "No", id:'food_no', value:"No" %>
		</div>
	</div>

	<div class='row'>
		<div class='col s12 m12 l12'>
			<div class="input-field" id='restrictions'>
				<%=f.label :food_restrictions, "" %>
				<%=f.text_area :food_restrictions, class: "materialize-textarea"%>
			</div>
		</div>
	</div>


	<!-- Comments -->
	<div class='row'>
	<div class='col s12 m12 l12'>
		<div class="attending">
          <div class="input-field">
           <%=f.label :comments, "Comments for the Bride and Groom " %>
           <%=f.text_area :comments, class: "materialize-textarea"%>
          </div>
			</div>
		</div>
  </div>
</div>

            <!-- Not attending  -->
        <div class="not-attending ">
					<div class='row'>

						<!-- Not attending comments -->
						<div class='center-align'>
		          <div class="input-field">
		            <%=f.label :not_coming, "Aww, :( Please feel free to leave a message for us! " %>
		              <%=f.text_area :not_coming, class: "materialize-textarea" %>
		                <div class="col-sm-8 "></div>
		          </div>
						</div>

						</div>
	        </div>

          <!-- Submit Button-->
        <div class='row'>
					<div class='center-align'>
            <%= button_tag( id: "form-modal-submit", :class => "rsvp-submit z-depth-2 btn waves-effect waves-light", data: { disable_with: "Please wait...", modal:"#myModal_#{user.id}", name:user.name, email:user.email}) do %>
             Submit <i class="mdi-content-send right"></i>
            <% end %>
					</div>
        </div>
        </form>
  <% end %>
</div>
	</div>
</div>

app/views/users/partials/_mobileRSVP.html.erb
<div id="Announcement" class='row'>
  <h1>Colin & Sarah</h1>
  <p>are getting</p>
  <h1>Married!</h1>
</div>

<div class="container">
  <table id="my-mobile-table">
    <thead>
      <th></th>
  	<th></th>
    </thead>
    <tbody>
  	  <% @user.each do |user| %>
        <tr>
          	<td>
            		<%=user.name %>
          	</td>
  			<td>
  			<a href= <%="#myModal_#{user.id}" %> class="rsvp-modal btn modal-trigger">RSVP</a>
  				<!-- RSVP Modal   -->
  				<div id=<%="myModal_#{user.id}" %> class="modal">
  					<%= render 'users/partials/edit', user: user %>
  				</div>

  		  </td>
        </tr>
        <% end %>
    </table>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class='container center'>
  <div class='card-panel'>
    <p>
      <strong>Name:</strong>
      <%= @user.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Food Restrictions:</strong>
      <% if @user.food == "Yes" %>
        <%= @user.food_restrictions %>
      <% else %>
        <%= @user.food %>
      <% end %>
    </p>

    <p>
      <strong>Attending:</strong>
        <%= @user.attending %>
    </p>

    <p>
      <strong>Meal:</strong>
        <%= @user.meal %>
    </p>


    <p>
      <strong>Comments:</strong>
        <%= @user.comments %>
    </p>
    <p>
      <%= link_to "Edit", edit_user_path(@user),class:"btn" %>
  </div>
</div>

app/views/users/update.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Attending:</strong>
    <%= @user.attending %>
</p>

<p>
  <strong>Meal:</strong>
    <%= @user.meal %>
</p>


<p>
  <strong>Comments:</strong>
    <%= @user.comments %>
</p>